### ISSUE TITLE
Do you have the same problem in training

### ISSUE THREAD

**Issue by 17000432** [stevehuanghe/SCA-CNN#2] opened 2018-12-11 12:11 UTC
When I was training, I got an error and couldn't find the price./image/train2014_resized/COCO_val2014_0000000000257.jpg.  I can't understand why the verified picture appears in the training folder.May I ask where the modification is needed? Thanks.

**Comment by stevehuanghe** [comment] 2018-12-12 02:55
I will look into it tomorrow and get back to you.

> When I was training, I got an error and couldn't find the price./image/train2014_resized/COCO_val2014_0000000000257.jpg. I can't understand why the verified picture appears in the training folder.May I ask where the modification is needed? Thanks.

**Comment by stevehuanghe** [comment] 2018-12-12 15:47
The problem is now fixed, please download the new code. The problem was that the output path in resize.py is not the same as the one in the config.py file, but now I have remove the resize.py and let pytorch do the resizing. Please feel free to change the setting is config.py if you have different paths to the data.

**Closed as completed** 2018-12-12 15:48 UTC
